site_name: Probo UI
site_description: “Type-safe Python UI framework for Django”
site_url: '' #https://example.com/probo-ui
repo_url: https://github.com/MojahiD-0-YouneSS/probo-ui
edit_uri: edit/main/docs/

theme:
  name: material
  palette: 
    # Light mode (default)
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs        # Top-level tabs for sections
    - navigation.sections    # Expandable sidebar sections
    - content.code.copy      # Copy button on code blocks

markdown_extensions:
  - admonition               # For "Note" or "Warning" block
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false   # <--- THIS IS THE KEY
            show_root_heading: true
  - include-markdown

  - gen-files:
      scripts:
        - gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
nav:
  - Home: index.md
  - API Reference: reference/probo/ 
  - User Guide: user_guide.md
  - Tutorial: tutorial.md
  - Development: dev_code.md
  - Release Note: realese_note.md
